export const myProjects = [
  {
    id: 1,
    projectTitle: "Basttet Travel — Egypt Travel Platform",
    liveUrl: "https://basttettravel.com/en",
    githubUrl: "https://github.com/mohamedAbu1/basttettravel",
    date: "2026",
    category: ["Website", "Travel platform", "Full-stack"],
    solutionType: "Website + Android application",
    projectSummary: "A complete travel product: a public website, an Android application, and an operations dashboard connected to the same backend.",
    platforms: [
      { name: "Website", detail: "Responsive full-stack web platform" },
      { name: "Android application", detail: "React Native application for mobile users" },
      { name: "Admin dashboard", detail: "Content, projects, messages, and operations management" },
    ],
    imgPaths: [
      "/uploads/projects/basttet-travel/01-home-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/02-home-desktop-alt-4k.jpg",
      "/uploads/projects/basttet-travel/03-about-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/04-contact-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/05-signup-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/06-login-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/07-trip-detail-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/08-trip-detail-lower-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/09-trips-horizontal-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/10-trips-grid-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/11-admin-dashboard-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/12-notifications-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/13-messages-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/14-home-mobile-4k.jpg",
      "/uploads/projects/basttet-travel/15-admin-dashboard-mobile-4k.jpg",
      "/uploads/projects/basttet-travel/16-trip-detail-mobile-4k.jpg",
      "/uploads/projects/basttet-travel/17-contact-mobile-4k.jpg",
      "/uploads/projects/basttet-travel/18-about-mobile-4k.jpg",
    ],
    technologies: ["Next.js", "React", "JavaScript", "Node.js", "Tailwind CSS", "MySQL"].map((name) => ({ name })),
    features: [
      "Curated Egypt trips and filtering",
      "Responsive desktop and mobile experience",
      "Trip detail galleries and planning flow",
      "Authentication and account states",
      "Operations dashboard and messaging",
      "Public contact and booking journey",
    ],
    connectedDeliverables: [{ title: 'Basttet Travel — Android Application', service: 'Android App', status: 'Delivered · Sold', url: 'https://expo.dev/accounts/mohamed_abu_1997/projects/basttettravelApp/builds/3fab67d6-e3a1-4d19-b87c-c091b98525d5', technologies: ['React Native', 'Expo', 'JavaScript'], imgPaths: [ '/uploads/projects/basttet-travel-android/01-home-dark-4k.jpg', '/uploads/projects/basttet-travel-android/02-home-light-4k.jpg', '/uploads/projects/basttet-travel-android/03-categories-4k.jpg', '/uploads/projects/basttet-travel-android/04-trip-detail-4k.jpg', '/uploads/projects/basttet-travel-android/05-login-dark-4k.jpg', '/uploads/projects/basttet-travel-android/06-login-light-4k.jpg', '/uploads/projects/basttet-travel-android/07-register-dark-4k.jpg', '/uploads/projects/basttet-travel-android/08-about-dark-4k.jpg', '/uploads/projects/basttet-travel-android/09-about-light-4k.jpg', '/uploads/projects/basttet-travel-android/10-contact-dark-4k.jpg', '/uploads/projects/basttet-travel-android/11-contact-light-4k.jpg' ] }],
  },
  {
    id: 2,
    clientName: "Imran Abdel Hareth",
    projectTitle: "One Time Life Travel — Luxury Egypt Travel Platform",
    liveUrl: "https://onetimelifetravel.com/en",
    githubUrl: "https://github.com/mohamedAbu1/onetimelifetravel",
    appUrl: "https://expo.dev/accounts/mohamed_abu_1997/projects/onetimelifetravel/builds/49506968-2780-43f6-a836-53584f731344",
    date: "2026",
    category: ["Website", "Android application", "Luxury travel"],
    solutionType: "Website + Android application",
    projectSummary: "A refined travel experience that turns Egyptian destinations into memorable stories through editorial design, intelligent discovery, and a seamless mobile journey.",
    platforms: [
      { name: "Website", detail: "Immersive full-stack travel platform" },
      { name: "Android application", detail: "Expo and React Native travel companion" },
    ],
    imgPaths: Array.from({ length: 30 }, (_, index) => `/uploads/projects/one-time-life-travel/${String(index + 1).padStart(2, "0")}.jpg`),
    technologies: ["Next.js", "React", "React Native", "Tailwind CSS", "MySQL", "Expo Go", "JavaScript"].map((name) => ({ name })),
    features: [
      "Editorial destination storytelling and luxury travel positioning",
      "Responsive website experience with seasonal visual themes",
      "A dedicated visual style system tailored to every occasion and seasonal campaign",
      "Trip discovery, filtering, and journey planning flows",
      "Android application for browsing and planning Egyptian journeys",
      "Authentication, profile, contact, and travel support touchpoints",
      "Operations dashboard for managing the travel business",
    ],
    connectedDeliverables: [{ title: "One Time Life Travel — Android Application", service: "Android App", status: "Delivered · Sold", url: "https://expo.dev/accounts/mohamed_abu_1997/projects/onetimelifetravel/builds/49506968-2780-43f6-a836-53584f731344", technologies: ["React Native", "Expo", "JavaScript"] }],
  },
  {
    id: 3,
    projectTitle: "UX/UI Resume Collection",
    date: "2026",
    category: ["UX/UI Design", "Resume design", "Visual systems"],
    solutionType: "Single design collection",
    projectSummary: "A curated collection of seven resume layouts exploring hierarchy, typography, and visual systems for different professional roles.",
    platforms: [{ name: "Design gallery", detail: "Ten resume concepts in one collection" }],
    imgPaths: [
      "/uploads/projects/uxui-resume-collection/Modern-Resume-768x1080.jpg",
      "/uploads/projects/uxui-resume-collection/Best-Resume-Template-Free-Download-MS-Word-.jpg",
      "/uploads/projects/uxui-resume-collection/modern-creative-professional-cv-template-designs_1286190-46.avif",
      "/uploads/projects/uxui-resume-collection/modern-creative-professional-cv-template-designs_1286190-54.avif",
      "/uploads/projects/uxui-resume-collection/OIP (5).webp",
      "/uploads/projects/uxui-resume-collection/Pro-CV-Template-Free-Download-MS-Word.jpg",
      "/uploads/projects/uxui-resume-collection/b5e01a126314783.612b2c2bbcc45.jpg",
    ],
    technologies: ["Figma", "UX/UI Design", "Typography", "Visual Design", "Responsive Layouts"].map((name) => ({ name })),
    features: ["Seven role-specific resume layouts", "Consistent visual design system", "Clear information hierarchy", "Professional typography and spacing"],
    connectedDeliverables: []
  },
  {
    id: 6,
    projectTitle: "Al-Aroum — Travel & Stays Platform",
    liveUrl: "https://al-apartments.vercel.app/",
    date: "2026",
    category: ["Website", "Travel & stays", "Property platform"],
    solutionType: "Responsive travel and property website",
    projectSummary: "Available for sale — $1,350. A polished travel and property discovery platform with destination storytelling, property listings, filtering, booking touchpoints, authentication, and responsive light and dark themes.",
    status: "Available for sale",
    availability: "Available for sale",
    price: 1350,
    currency: "USD",
    isSold: false,
    platforms: [
      { name: "Website", detail: "Responsive travel and property discovery experience" },
      { name: "Mobile experience", detail: "Optimized browsing, filtering, and inquiry flows" },
    ],
    imgPaths: [
      "/uploads/projects/al-aroum/01-contact-dark.jpg",
      "/uploads/projects/al-aroum/02-listings-dark.jpg",
      "/uploads/projects/al-aroum/03-property-detail-dark.jpg",
      "/uploads/projects/al-aroum/04-sign-in.jpg",
      "/uploads/projects/al-aroum/05-create-account.jpg",
      "/uploads/projects/al-aroum/06-mobile-destinations.jpg",
      "/uploads/projects/al-aroum/07-mobile-listings.jpg",
      "/uploads/projects/al-aroum/08-mobile-home-dark.jpg",
      "/uploads/projects/al-aroum/09-mobile-home-dark-alt.jpg",
      "/uploads/projects/al-aroum/10-listings-light.jpg",
      "/uploads/projects/al-aroum/11-contact-light.jpg",
      "/uploads/projects/al-aroum/12-destinations-light.jpg",
      "/uploads/projects/al-aroum/13-home-sections-light.jpg",
    ],
    technologies: ["Next.js", "React", "JavaScript", "Responsive UI", "Authentication", "Vercel"].map((name) => ({ name })),
    features: [
      "Travel destinations and experience discovery",
      "Property listing search, filtering, and sorting",
      "Property detail pages with inquiry actions",
      "Responsive desktop and mobile layouts",
      "Light and dark visual themes",
      "Sign-in and account creation flows",
    ],
    connectedDeliverables: [],
  },];
export const images = {
  dark: ["/images/mohamedAbou.webp", "/images/MohamedAbu.webp"],
  light: ["/images/MyPic.webp", "/images/Mypic2.webp"],
};




