export const myProjects = [
  {
    id: 1,
    projectTitle: "Basttet Travel — Egypt Travel Platform",
    liveUrl: "https://basttettravel.com/en",
    githubUrl: "https://github.com/mohamedAbu1/basttettravel",
    date: "2026",
    category: ["Website", "Travel platform", "Full-stack"],
    solutionType: "Website + Android application",
    projectSummary: "A complete travel product: a public website, an Android application, and an operations dashboard connected to the same backend.",
    platforms: [
      { name: "Website", detail: "Responsive full-stack web platform" },
      { name: "Android application", detail: "React Native application for mobile users" },
      { name: "Admin dashboard", detail: "Content, projects, messages, and operations management" },
    ],
    imgPaths: [
      "/uploads/projects/basttet-travel/01-home-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/02-home-desktop-alt-4k.jpg",
      "/uploads/projects/basttet-travel/03-about-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/04-contact-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/05-signup-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/06-login-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/07-trip-detail-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/08-trip-detail-lower-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/09-trips-horizontal-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/10-trips-grid-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/11-admin-dashboard-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/12-notifications-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/13-messages-desktop-4k.jpg",
      "/uploads/projects/basttet-travel/14-home-mobile-4k.jpg",
      "/uploads/projects/basttet-travel/15-admin-dashboard-mobile-4k.jpg",
      "/uploads/projects/basttet-travel/16-trip-detail-mobile-4k.jpg",
      "/uploads/projects/basttet-travel/17-contact-mobile-4k.jpg",
      "/uploads/projects/basttet-travel/18-about-mobile-4k.jpg",
      "/uploads/projects/basttet-travel-android/01-home-dark-4k.jpg",
      "/uploads/projects/basttet-travel-android/02-home-light-4k.jpg",
      "/uploads/projects/basttet-travel-android/03-categories-4k.jpg",
      "/uploads/projects/basttet-travel-android/04-trip-detail-4k.jpg",
      "/uploads/projects/basttet-travel-android/05-login-dark-4k.jpg",
      "/uploads/projects/basttet-travel-android/06-login-light-4k.jpg",
      "/uploads/projects/basttet-travel-android/07-register-dark-4k.jpg",
      "/uploads/projects/basttet-travel-android/08-about-dark-4k.jpg",
      "/uploads/projects/basttet-travel-android/09-about-light-4k.jpg",
      "/uploads/projects/basttet-travel-android/10-contact-dark-4k.jpg",
      "/uploads/projects/basttet-travel-android/11-contact-light-4k.jpg",
    ],
    technologies: ["Next.js", "React", "JavaScript", "Node.js", "Tailwind CSS", "MySQL"].map((name) => ({ name })),
    features: [
      "Curated Egypt trips and filtering",
      "Responsive desktop and mobile experience",
      "Trip detail galleries and planning flow",
      "Authentication and account states",
      "Operations dashboard and messaging",
      "Public contact and booking journey",
    ],
    connectedDeliverables: [{ title: 'Basttet Travel — Android Application', service: 'Android App', status: 'Delivered · Sold', url: 'https://expo.dev/accounts/mohamed_abu_1997/projects/basttettravelApp/builds/3fab67d6-e3a1-4d19-b87c-c091b98525d5', technologies: ['React Native', 'Expo', 'JavaScript'] }],
  },
];
export const images = {
  dark: ["/images/mohamedAbou.webp", "/images/MohamedAbu.webp"],
  light: ["/images/MyPic.webp", "/images/Mypic2.webp"],
};



